### ISSUE TITLE
Keyboard not changes after code modification

### ISSUE THREAD

**Issue by vitjaz** [feathers-studio/telegraf-docs#12]
Hi there! 

I took the keyboard example from the example in this repository. 

```js
bot.command("custom", async ctx => {
	return await ctx.reply(
		"Custom buttons keyboard",
		Markup.keyboard([
			["🔍 Search", "😎 Popular"], // Row1 with 2 buttons
			["☸ Setting", "📞 Feedback"], // Row2 with 2 buttons
			["📢 Ads", "⭐️ Rate us", "👥 Share"], // Row3 with 3 buttons
		])
			.oneTime()
			.resize(),
	);
});
```
![image](https://github.com/feathers-studio/telegraf-docs/assets/47814045/5580d31f-cce0-4f70-9810-e4f86d62df4b)

And I got the expected result, but then I changed this code, but the bot did not react in any way. Restarting the bot didn't help either. 
My own variant:
```js
bot.command("custom", async ctx => {
	return await ctx.reply(
		"Custom buttons keyboard",
		Markup.keyboard([
			["🔍 Статус API валют", "😎 Текущий курс"], // Row1 with 2 buttons
		])
			.oneTime()
			.resize(),
	);
});
```

What's my mistake?

**Comment by MKRhere** [comment]
Did you send the command again? Editing the code alone won't change the keyboards. Telegram bots are not websites.
