### ISSUE TITLE
AWS lambda example returns `Internal Server Error`

### ISSUE THREAD

**Issue by maschlr** [feathers-studio/telegraf-docs#2]
HI!
I've deployed the [AWS example](https://github.com/feathers-studio/telegraf-docs/tree/master/examples/functions/aws-lambda). All steps succeed and I can see the lambda function + the API gateway in the AWS console.

Testing further via Postman given the examples in the [Telegram Bot API FAQ](https://core.telegram.org/bots/webhooks#testing-your-bot-with-updates), I receive a `Internal Server Error` (`POST`ing to random enpoints on the same AWS domain gives a `Not found`).

Is the example still functional?

**Comment by maschlr** [comment]
Found the error, my mistake: the environment variable was not loaded.

There's a simple [plugin for serverless](https://github.com/neverendingqs/serverless-dotenv-plugin) that loads everything defined in `.env`. I see I cannot open PRs on this repo. Maybe add that plugin to the example?

**Comment by MKRhere** [comment]
PRs are open; fork the repo, make your changes, and you'll see a prompt to PR it back. You can also click the pencil icon in a file and it'll automatically nudge you to fork.
