### ISSUE TITLE
Hello, i not can find in documentation this action 

### ISSUE THREAD

**Issue by gravitymir** [feathers-studio/telegraf-docs#6]
Action
https://stackoverflow.com/questions/61520440/pretending-that-telegram-bot-is-typing
https://core.telegram.org/method/messages.setTyping

**Comment by MKRhere** [comment]
Telegraf is a Bot API framework. What you're linking to is MTProto (the Telegram client API).
You should refer to this page for the Bot API: https://core.telegram.org/bots/api

That said, this can be done with Telegraf with the following code:
```TS
ctx.sendChatAction("typing");

// or

bot.telegram.sendChatAction(chatId, "upload_video");
```

See other options for sendChatAction in the Bot API docs: https://core.telegram.org/bots/api#sendchataction
